# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
version: 2

builds:
  - ldflags: -s -w -X "corrupt952/closest.Version={{.Version}}"
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

# Packging only binary
# FYI: https://goreleaser.com/customization/archive/#packaging-only-the-binaries
archives:
  - files:
      - none*
